GET http://localhost:3000/states/
###

GET http://localhost:3000/districts/
###

GET http://localhost:3000/states/5
###

POST http://localhost:3000/districts/
Content-Type: application/json

{
  "districtName": "Warangal",
  "stateId": 29,
  "cases": 25250,
  "cured": 2000,
  "active": 23250,
  "deaths": 1000
}
###

GET http://localhost:3000/districts/762
###

DELETE http://localhost:3000/districts/763
###

PUT http://localhost:3000/districts/762
Content-Type: application/json

{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}
###

GET http://localhost:3000/states/6/stats/
###

GET http://localhost:3000/districts/4/details/
###